# Generated by Django 3.2.12 on 2024-02-21 16:54

import cabroApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.CharField(default=cabroApp.models.generate_id, max_length=6, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=200)),
                ('date_naiss', models.DateField()),
                ('mot_passe', models.CharField(max_length=8)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('id_demande_stage', models.CharField(max_length=50, null=True)),
                ('date_enregistre', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(null=True)),
                ('type', models.CharField(default='STAGIAIRE', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabroApp.collaborateur')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCollaborateur',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellé', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('delai', models.CharField(max_length=2)),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('collaborateurs', models.ManyToManyField(to='cabroApp.Collaborateur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabroApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Piece_jointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('file', models.FilePathField(path=None)),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabroApp.tache')),
            ],
        ),
    ]
