# Generated by Django 3.2.12 on 2024-02-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabroApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='collaborateurs',
        ),
        migrations.CreateModel(
            name='Assignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabroApp.collaborateur')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabroApp.tache')),
            ],
        ),
    ]
