# Generated by Django 3.2.12 on 2024-02-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabroApp', '0003_auto_20240222_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(default='En cours', max_length=50),
        ),
    ]
